- hosts: all
  roles:
    - bindep
  vars:
    bindep_file: /home/zuul/src/opendev.org/openstack/openstack-chef/bindep.txt

- hosts: all
  vars:
    release: 0.18.3
    chef_workstation: chef-workstation_{{ release }}-1_amd64.deb
  tasks:
  - name: Fetch chef-workstation package
    get_url:
      dest: /tmp/{{ chef_workstation }}
      url: https://packages.chef.io/files/stable/chef-workstation/{{ release }}/ubuntu/18.04/{{ chef_workstation }}
  - name: Install chef-workstation package
    shell: dpkg -i /tmp/{{ chef_workstation }}
    become: yes
  - name: Show chef environment, accept chef license as side effect
    shell: chef env --chef-license accept
    become: yes
  - name: Install newer fog-openstack gem
    shell: chef gem install fog-openstack --version '~> 1.0.0' --no-user-install -N
    become: yes
